spring:
  application:
    name: fileUploaderService

  datasource:
    url: jdbc:postgresql://localhost:5432/fileStorage
    username: nurgisaserikkali
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8030

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: uploaded-files

async:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: health,info
